// ReygorillaCollector - Initial Games Database
// This database pre-populates the collector's list on first load to showcase the app.

const INITIAL_GAMES = [
  // 1ª y 2ª Generación
  {
    id: "game_odyssey_pong",
    title: "Table Tennis",
    consoleId: "odyssey",
    generation: "gen1_2",
    region: "USA",
    format: "Cartucho Analógico",
    condition: "Loose",
    rating: 4,
    status: "owned",
    price: 150,
    notes: "Tarjeta de juego Nº 1. Requiere la plantilla de plástico para el televisor. ¡Una pieza de historia!",
    dateAdded: "2026-01-15"
  },
  {
    id: "game_atari2600_pitfall",
    title: "Pitfall!",
    consoleId: "atari2600",
    generation: "gen1_2",
    region: "USA",
    format: "Cartucho",
    condition: "CIB",
    rating: 5,
    status: "owned",
    price: 45,
    notes: "Obra maestra de Activision para la Atari 2600. Caja y manual en muy buen estado.",
    dateAdded: "2026-02-10"
  },
  {
    id: "game_colecovision_donkey",
    title: "Donkey Kong",
    consoleId: "colecovision",
    generation: "gen1_2",
    region: "EUR",
    format: "Cartucho",
    condition: "Boxed",
    rating: 5,
    status: "owned",
    price: 35,
    notes: "Impresionante port del arcade de Nintendo. Prácticamente idéntico al mueble original.",
    dateAdded: "2026-03-01"
  },
  {
    id: "game_intellivision_astrosmash",
    title: "Astrosmash",
    consoleId: "intellivision",
    generation: "gen1_2",
    region: "USA",
    format: "Cartucho",
    condition: "CIB",
    rating: 4,
    status: "owned",
    price: 25,
    notes: "Incluye las dos plantillas de plástico para meter en el teclado numérico del mando.",
    dateAdded: "2026-03-12"
  },
  {
    id: "game_atari5200_breakout",
    title: "Super Breakout",
    consoleId: "atari5200",
    generation: "gen1_2",
    region: "USA",
    format: "Cartucho",
    condition: "Loose",
    rating: 3,
    status: "wishlist",
    price: 20,
    notes: "Buscando una copia CIB para poder disfrutarlo con los mandos analógicos de la 5200.",
    dateAdded: "2026-04-05"
  },

  // 3ª Generación
  {
    id: "game_nes_mario3",
    title: "Super Mario Bros. 3",
    consoleId: "nes",
    generation: "gen3",
    region: "EUR",
    format: "Cartucho",
    condition: "CIB",
    rating: 5,
    status: "owned",
    price: 85,
    notes: "Versión PAL española. Caja de cartón ligeramente desgastada en las pestañas, pero con manual original.",
    dateAdded: "2025-11-20"
  },
  {
    id: "game_mastersystem_alex",
    title: "Alex Kidd in Miracle World",
    consoleId: "mastersystem",
    generation: "gen3",
    region: "EUR",
    format: "Cartucho",
    condition: "Boxed",
    rating: 4,
    status: "owned",
    price: 30,
    notes: "El clásico de Master System. Viene pre-instalado en la memoria de la consola, pero tengo el cartucho físico.",
    dateAdded: "2025-12-05"
  },
  {
    id: "game_atari7800_foodfight",
    title: "Food Fight",
    consoleId: "atari7800",
    generation: "gen3",
    region: "USA",
    format: "Cartucho",
    condition: "Loose",
    rating: 4,
    status: "owned",
    price: 28,
    notes: "Divertidísimo arcade portado de forma magistral. Los gráficos son geniales.",
    dateAdded: "2026-04-18"
  },

  // 4ª Generación
  {
    id: "game_snes_marioworld",
    title: "Super Mario World",
    consoleId: "snes",
    generation: "gen4",
    region: "EUR",
    format: "Cartucho",
    condition: "CIB",
    rating: 5,
    status: "completed",
    price: 90,
    notes: "Juego de lanzamiento de SNES. 100% completado con las 96 salidas. ¡Esencial!",
    dateAdded: "2025-09-10"
  },
  {
    id: "game_megadrive_sonic2",
    title: "Sonic the Hedgehog 2",
    consoleId: "megadrive",
    generation: "gen4",
    region: "EUR",
    format: "Cartucho",
    condition: "CIB",
    rating: 5,
    status: "completed",
    price: 40,
    notes: "Caja de plástico negra de Sega clásica, manual en múltiples idiomas. En perfecto estado de conservación.",
    dateAdded: "2025-10-02"
  },
  {
    id: "game_pcengine_rondo",
    title: "Castlevania: Rondo of Blood",
    consoleId: "pcengine",
    generation: "gen4",
    region: "JPN",
    format: "CD-ROM",
    condition: "CIB",
    rating: 5,
    status: "owned",
    price: 180,
    notes: "Para la PC Engine Super CD-ROM². Edición japonesa original con spinecard (Obi). Una joya de coleccionista.",
    dateAdded: "2026-02-28"
  },
  {
    id: "game_neogeo_metalslug",
    title: "Metal Slug",
    consoleId: "neogeo",
    generation: "gen4",
    region: "JPN",
    format: "Cartucho",
    condition: "Loose",
    rating: 5,
    status: "wishlist",
    price: 2500,
    notes: "El Santo Grial. Muy difícil de conseguir original a precio razonable. Actualmente en lista de deseos.",
    dateAdded: "2026-05-01"
  },
  {
    id: "game_gameboy_tetris",
    title: "Tetris",
    consoleId: "gameboy",
    generation: "gen4",
    region: "GBL",
    format: "Cartucho",
    condition: "Loose",
    rating: 5,
    status: "owned",
    price: 15,
    notes: "El cartucho con el que empezó todo. Conserva la pegatina frontal original en buen estado.",
    dateAdded: "2025-08-15"
  },
  {
    id: "game_gamegear_sonicchaos",
    title: "Sonic Chaos",
    consoleId: "gamegear",
    generation: "gen4",
    region: "EUR",
    format: "Cartucho",
    condition: "Boxed",
    rating: 4,
    status: "owned",
    price: 35,
    notes: "Viene en su caja de cartón azul de Sega. Incluye el protector de plástico para el cartucho.",
    dateAdded: "2026-01-20"
  },
  {
    id: "game_lynx_blue",
    title: "Blue Lightning",
    consoleId: "lynx",
    generation: "gen4",
    region: "USA",
    format: "Cartucho",
    condition: "Loose",
    rating: 4,
    status: "owned",
    price: 22,
    notes: "Espectacular simulador de vuelo que demostraba la capacidad de escalado de sprites de la portátil.",
    dateAdded: "2026-04-10"
  },

  // 5ª Generación
  {
    id: "game_ps1_mgs",
    title: "Metal Gear Solid",
    consoleId: "ps1",
    generation: "gen5",
    region: "EUR",
    format: "CD-ROM",
    condition: "CIB",
    rating: 5,
    status: "completed",
    price: 75,
    notes: "Edición PAL España con doblaje legendario en castellano. Discos sin apenas arañazos. Incluye demo de Silent Hill.",
    dateAdded: "2025-09-05"
  },
  {
    id: "game_n64_mario64",
    title: "Super Mario 64",
    consoleId: "n64",
    generation: "gen5",
    region: "EUR",
    format: "Cartucho",
    condition: "CIB",
    rating: 5,
    status: "completed",
    price: 95,
    notes: "Caja PAL España. El juego que definió las tres dimensiones. Conserva el manual de instrucciones impecable.",
    dateAdded: "2025-09-12"
  },
  {
    id: "game_saturn_nights",
    title: "Nights into Dreams...",
    consoleId: "saturn",
    generation: "gen5",
    region: "EUR",
    format: "CD-ROM",
    condition: "CIB",
    rating: 5,
    status: "owned",
    price: 60,
    notes: "Viene en la caja de cartón grande junto con el mando analógico 3D de Sega Saturn.",
    dateAdded: "2026-01-05"
  },
  {
    id: "game_3do_roadrash",
    title: "Road Rash",
    consoleId: "3do",
    generation: "gen5",
    region: "USA",
    format: "CD-ROM",
    condition: "CIB",
    rating: 4,
    status: "owned",
    price: 70,
    notes: "La mejor versión de este clásico de motos con vídeos reales y banda sonora de grunge espectacular.",
    dateAdded: "2026-04-30"
  },
  {
    id: "game_jaguar_tempest",
    title: "Tempest 2000",
    consoleId: "jaguar",
    generation: "gen5",
    region: "USA",
    format: "Cartucho",
    condition: "Boxed",
    rating: 5,
    status: "owned",
    price: 110,
    notes: "Obra maestra de Jeff Minter. Indispensable para cualquier coleccionista de Jaguar. Música tecno sublime.",
    dateAdded: "2026-05-15"
  },
  {
    id: "game_neogeocd_kof98",
    title: "The King of Fighters '98",
    consoleId: "neogeocd",
    generation: "gen5",
    region: "JPN",
    format: "CD-ROM",
    condition: "CIB",
    rating: 5,
    status: "owned",
    price: 65,
    notes: "Edición japonesa con manual grueso ilustrado y carátula preciosa. Tiempos de carga notables pero banda sonora AST espectacular.",
    dateAdded: "2026-03-25"
  },
  {
    id: "game_gbc_pokemongold",
    title: "Pokémon Edición Oro",
    consoleId: "gbc",
    generation: "gen5",
    region: "EUR",
    format: "Cartucho",
    condition: "CIB",
    rating: 5,
    status: "owned",
    price: 120,
    notes: "Edición española. Pila interna recién cambiada para poder guardar partida y usar el reloj interno.",
    dateAdded: "2025-11-15"
  },

  // 6ª Generación
  {
    id: "game_dreamcast_shenmue",
    title: "Shenmue",
    consoleId: "dreamcast",
    generation: "gen6",
    region: "EUR",
    format: "GD-ROM",
    condition: "CIB",
    rating: 5,
    status: "playing",
    price: 80,
    notes: "Estuche de cartón exterior algo desgastado, pero los 4 estuches de plástico interiores y manuales están perfectos.",
    dateAdded: "2025-12-18"
  },
  {
    id: "game_ps2_shadow",
    title: "Shadow of the Colossus",
    consoleId: "ps2",
    generation: "gen6",
    region: "EUR",
    format: "DVD-ROM",
    condition: "CIB",
    rating: 5,
    status: "completed",
    price: 45,
    notes: "Edición especial de cartón que incluye postales de arte. Una de las mayores joyas artísticas de PS2.",
    dateAdded: "2025-10-10"
  },
  {
    id: "game_gamecube_smash",
    title: "Super Smash Bros. Melee",
    consoleId: "gamecube",
    generation: "gen6",
    region: "EUR",
    format: "MiniDVD",
    condition: "CIB",
    rating: 5,
    status: "owned",
    price: 70,
    notes: "Excelente juego de lucha multijugador. Carátula limpia y disco impecable. Versión Player's Choice.",
    dateAdded: "2025-10-25"
  },
  {
    id: "game_xbox_halo",
    title: "Halo: Combat Evolved",
    consoleId: "xbox",
    generation: "gen6",
    region: "EUR",
    format: "DVD-ROM",
    condition: "CIB",
    rating: 5,
    status: "completed",
    price: 25,
    notes: "Edición clásica de caja verde de Xbox. El juego que redefinió los shooters en consola.",
    dateAdded: "2025-11-01"
  },
  {
    id: "game_gba_ariasorrow",
    title: "Castlevania: Aria of Sorrow",
    consoleId: "gba",
    generation: "gen6",
    region: "EUR",
    format: "Cartucho",
    condition: "Sealed",
    rating: 5,
    status: "owned",
    price: 320,
    notes: "Precintado de fábrica con la tira oficial de Nintendo roja. La joya de mi colección de portátiles.",
    dateAdded: "2026-05-20"
  }
];

// Export to make it accessible in both ES modules and globally if script tag is used
if (typeof module !== 'undefined' && module.exports) {
  module.exports = { INITIAL_GAMES };
}
